import type { Metadata } from "next";
import { Source_Code_Pro } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const sourcecodepro = Source_Code_Pro({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Stoyan Nikolov portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sourcecodepro.className} bg-mainbg`} >
        <Navbar />
        {children}</body>
    </html>
  );
}
